name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build (Node ${{ matrix.node-version }} - Nest ${{ matrix.nest-version }} - Mongo ${{ matrix.mongo-version }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        nest-version: [^9.0.0, ^10.0.0] # ^8.0.0 unsupported
        mongo-version: [^4.0.0, ^5.0.0, ^6.0.0]

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup: pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: "Setup: Node ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Dependencies
        run: pnpm install --frozen-lockfile

      - name: "Dependencies: peer"
        run: |
          pnpm install \
            @nestjs/common@${{ matrix.nest-version }} \
            @nestjs/core@${{ matrix.nest-version }} \
            @nestjs/testing@${{ matrix.nest-version }} \
            @golee/mongo-nest mongodb@${{matrix.mongo-version}}

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

  should_publish_on_npm:
    name: check if NPM_TOKEN is set in github secrets
    runs-on: ubuntu-latest
    outputs:
      SHOULD_PUBLISH_ON_NPM: ${{ steps.should_publish_on_npm_job.outputs.SHOULD_PUBLISH_ON_NPM }}
    steps:
      - id: should_publish_on_npm_job
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "SHOULD_PUBLISH_ON_NPM: ${{ env.NPM_TOKEN != '' }}"
          echo "SHOULD_PUBLISH_ON_NPM=${{ env.NPM_TOKEN != '' }}" >> $GITHUB_OUTPUT

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build, should_publish_on_npm]

    permissions:
      id-token: write
      contents: write

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-publish]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup: pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: "Setup: Node"
        uses: actions/setup-node@v4
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'true'
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Release: Prepare"
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github'
          pnpm version patch

      - name: Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'true'

        run: |
          npm install -g npm@latest
          pnpm publish --no-git-checks

      - name: "Release: Perform"
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'true'
        run: git push --follow-tags --no-verify

      - run: echo "tag=main-$(echo $GITHUB_SHA | cut -c1-7)" >> "$GITHUB_OUTPUT"
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'false'
        id: tag
      - name: Zip mongo-nest directory
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'false'
        run: |
          pnpm pack --out ./mongo-nest.tgz
      - name: Create and publish versions on github
        if: needs.should_publish_on_npm.outputs.SHOULD_PUBLISH_ON_NPM == 'false'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag.outputs.tag }}
          files: mongo-nest.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
